export interface GuardrailCardInfo {
  id: string;
  name: string;
  description: string;
  category: "litellm" | "partner";
  subcategory?: string;
  logo: string;
  tags: string[];
  eval?: {
    f1: number;
    precision: number;
    recall: number;
    testCases: number;
    latency: string;
  };
  providerKey?: string;
}

const ASSET_PREFIX = "/ui/assets/logos/";

export const LITELLM_CONTENT_FILTER_CARDS: GuardrailCardInfo[] = [
  {
    id: "cf_denied_financial",
    name: "Conselho Financeiro Bloqueado",
    description:
      "Detecta solicitações de conselho financeiro personalizado, recomendações de investimento ou planejamento financeiro.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Bloqueador de Tópico"],
    eval: {
      f1: 100.0,
      precision: 100.0,
      recall: 100.0,
      testCases: 207,
      latency: "<0.1ms",
    },
  },
  {
    id: "cf_denied_insults",
    name: "Insultos e Ataques Pessoais",
    description: "Detecta insultos, chamadas de atenção e ataques pessoais direcionados ao chatbot, equipe ou outras pessoas.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Bloqueador de Tópico"],
    eval: {
      f1: 100.0,
      precision: 100.0,
      recall: 100.0,
      testCases: 299,
      latency: "<0.1ms",
    },
  },
  {
    id: "cf_denied_legal",
    name: "Conselho Legal Bloqueado",
    description: "Detecta solicitações de conselho jurídico não autorizado, análise de casos ou recomendações legais.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Bloqueador de Tópico"],
  },
  {
    id: "cf_denied_medical",
    name: "Conselho Médico Bloqueado",
    description: "Detecta solicitações de diagnóstico médico, recomendações de tratamento ou conselhos de saúde.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Bloqueador de Tópico"],
  },
  {
    id: "cf_harmful_violence",
    name: "Violência Prejudicial",
    description: "Detecta conteúdo relacionado à violência, planejamento criminal, ataques e ameaças violentas.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Segurança"],
  },
  {
    id: "cf_harmful_self_harm",
    name: "Auto-Dano Prejudicial",
    description: "Detecta conteúdo relacionado a auto-dano, suicídio e comportamento autodestrutivo perigoso.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Segurança"],
  },
  {
    id: "cf_harmful_child_safety",
    name: "Segurança Infantil Prejudicial",
    description: "Detecta conteúdo que poderia colocar em perigo a segurança infantil ou explorar menores.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Segurança"],
  },
  {
    id: "cf_harmful_illegal_weapons",
    name: "Armas Ilegais Prejudiciais",
    description: "Detecta conteúdo relacionado à fabricação, distribuição ou aquisição de armas ilegais.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Segurança"],
  },
  {
    id: "cf_bias_gender",
    name: "Viés: Gênero",
    description: "Detecta discriminação baseada em gênero, estereótipos e linguagem tendenciosa.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Viés"],
  },
  {
    id: "cf_bias_racial",
    name: "Viés: Racial",
    description: "Detecta discriminação racial, estereótipos e conteúdo tendencioso racial.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Viés"],
  },
  {
    id: "cf_bias_religious",
    name: "Viés: Religioso",
    description: "Detecta discriminação religiosa, intolerância e conteúdo tendencioso religioso.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Viés"],
  },
  {
    id: "cf_bias_sexual_orientation",
    name: "Viés: Orientação Sexual",
    description: "Detecta discriminação baseada em orientação sexual e conteúdo tendencioso relacionado.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Viés"],
  },
  {
    id: "cf_prompt_injection_jailbreak",
    name: "Injeção de Prompt: Quebra de Sistema",
    description: "Detecta tentativas de quebra do sistema projetadas para contornar diretrizes de segurança e restrições da IA.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Injeção de Prompt"],
  },
  {
    id: "cf_prompt_injection_data_exfil",
    name: "Injeção de Prompt: Exfiltração de Dados",
    description: "Detecta tentativas de extrair dados sensíveis por meio de manipulação de prompt.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Injeção de Prompt"],
  },
  {
    id: "cf_prompt_injection_sql",
    name: "Injeção de Prompt: SQL",
    description: "Detecta tentativas de injeção SQL embutidas em prompts.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Injeção de Prompt"],
  },
  {
    id: "cf_prompt_injection_malicious_code",
    name: "Injeção de Prompt: Código Malicioso",
    description: "Detecta tentativas de injetar código malicioso por meio de prompts.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Injeção de Prompt"],
  },
  {
    id: "cf_prompt_injection_system_prompt",
    name: "Injeção de Prompt: Prompt do Sistema",
    description: "Detecta tentativas de extrair ou substituir prompts do sistema.",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Injeção de Prompt"],
  },
  {
    id: "cf_toxic_abuse",
    name: "Linguagem Tóxica e Abusiva",
    description: "Detecta linguagem tóxica, abusiva e odiosa em múltiplos idiomas (EN, AU, DE, ES, FR).",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Tóxicidade"],
  },
  {
    id: "cf_patterns",
    name: "Correspondência de Padrões",
    description:
      "Detecta e bloqueia padrões de dados sensíveis como SSNs, números de cartão de crédito, chaves de API e padrões regex personalizados.",
    category: "litellm",
    subcategory: "Padrões",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["PII", "Regex", "Proteção de Dados"],
  },
  {
    id: "cf_keywords",
    name: "Bloqueio de Palavras-Chave",
    description:
      "Bloqueia ou mascara conteúdo contendo palavras-chave ou frases específicas. Envie listas de palavras personalizadas ou adicione termos individuais.",
    category: "litellm",
    subcategory: "Palavras-Chave",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Palavras-Chave", "Lista de Bloqueio"],
  },
  {
    id: "block_code_execution",
    name: "Bloqueio de Execução de Código",
    description:
      "Detecta blocos de código cercados em markdown em requisições e respostas. Bloqueia ou mascara código executável (ex. Python, JavaScript, Bash) por linguagem com confiança configurável.",
    category: "litellm",
    subcategory: "Segurança de Código",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Código", "Segurança", "Injeção de Prompt"],
  },
  {
    id: "cf_competitor_intent",
    name: "Bloqueio de Nome de Competidor",
    description:
      "Bloqueia ou reformula a intenção de comparação e rankeamento de competidores. Detecta quando usuários pedem para comparar ou recomendar competidores (listas de companhias aéreas ou competidores genéricos).",
    category: "litellm",
    subcategory: "Categoria de Conteúdo",
    logo: `${ASSET_PREFIX}litellm_logo.jpg`,
    tags: ["Categoria de Conteúdo", "Competidor", "Bloqueador de Tópico"],
  },
];

export const PARTNER_GUARDRAIL_CARDS: GuardrailCardInfo[] = [
  {
    id: "presidio",
    name: "Presidio PII",
    description:
      "Microsoft Presidio para detecção e anonimização de PII. Suporta 30+ tipos de entidades com ações configuráveis.",
    category: "partner",
    logo: `${ASSET_PREFIX}microsoft_azure.svg`,
    tags: ["PII", "Microsoft"],
    providerKey: "PresidioPII",
  },
  {
    id: "bedrock",
    name: "Guardrail do Bedrock",
    description: "Guardrails do AWS Bedrock para filtragem de conteúdo, evitação de tópicos e detecção de informações sensíveis.",
    category: "partner",
    logo: `${ASSET_PREFIX}bedrock.svg`,
    tags: ["AWS", "Segurança de Conteúdo"],
    providerKey: "Bedrock",
  },
  {
    id: "lakera",
    name: "Lakera",
    description: "Plataforma de segurança de IA protegendo contra injeções de prompt, vazamento de dados e conteúdo prejudicial.",
    category: "partner",
    logo: `${ASSET_PREFIX}lakeraai.jpeg`,
    tags: ["Segurança", "Injeção de Prompt"],
    providerKey: "Lakera",
  },
  {
    id: "openai_moderation",
    name: "Moderação do OpenAI",
    description: "API de moderação de conteúdo do OpenAI para detecção de conteúdo prejudicial em múltiplas categorias.",
    category: "partner",
    logo: `${ASSET_PREFIX}openai_small.svg`,
    tags: ["Moderação de Conteúdo", "OpenAI"],
  },
  {
    id: "google_model_armor",
    name: "Model Armor do Google Cloud",
    description: "Serviço de proteção de modelo do Google Cloud para implantações seguras e responsáveis de IA.",
    category: "partner",
    logo: `${ASSET_PREFIX}google.svg`,
    tags: ["Google Cloud", "Segurança"],
  },
  {
    id: "guardrails_ai",
    name: "Guardrails AI",
    description: "Framework de código aberto para adicionar garantias estruturais, de tipo e qualidade às saídas de LLMs.",
    category: "partner",
    logo: `${ASSET_PREFIX}guardrails_ai.jpeg`,
    tags: ["Código Aberto", "Validação"],
  },
  {
    id: "zscaler",
    name: "Zscaler AI Guard",
    description: "Segurança de IA corporativa do Zscaler para monitoramento e proteção de cargas de trabalho de IA/ML.",
    category: "partner",
    logo: `${ASSET_PREFIX}zscaler.svg`,
    tags: ["Empresarial", "Segurança"],
  },
  {
    id: "panw",
    name: "PANW Prisma AIRS",
    description: "Segurança de tempo de execução de IA do Palo Alto Networks Prisma para proteger aplicações de IA em produção.",
    category: "partner",
    logo: `${ASSET_PREFIX}palo_alto_networks.jpeg`,
    tags: ["Empresarial", "Segurança"],
  },
  {
    id: "cisco_ai_defense",
    name: "Cisco AI Defense",
    description:
      "API de Inspeção Cisco AI Defense para proteção em tempo de execução: injeção de prompt, PII/PCI/PHI, assédio, discurso de ódio, palavrões, violência e detecção de código.",
    category: "partner",
    logo: `${ASSET_PREFIX}cisco.png`,
    tags: ["Empresarial", "Segurança", "Injeção de Prompt", "PII"],
    providerKey: "CiscoAiDefense",
  },
  {
    id: "noma",
    name: "Noma Security",
    description: "Plataforma de segurança de IA para detecção e prevenção de ameaças e vulnerabilidades específicas de IA.",
    category: "partner",
    logo: `${ASSET_PREFIX}noma_security.png`,
    tags: ["Segurança", "Detecção de Ameaças"],
  },
  {
    id: "aporia",
    name: "Aporia AI",
    description: "Guardrails de IA em tempo real para detecção de alucinações, controle de tópicos e aplicação de políticas.",
    category: "partner",
    logo: `${ASSET_PREFIX}aporia.png`,
    tags: ["Alucinação", "Política"],
  },
  {
    id: "aim",
    name: "AIM Guardrail",
    description: "Guardrails da AIM Security para detecção e mitigação abrangente de ameaças de IA.",
    category: "partner",
    logo: `${ASSET_PREFIX}aim_security.jpeg`,
    tags: ["Segurança", "Detecção de Ameaças"],
  },
  {
    id: "cato_networks",
    name: "Cato Networks Guardrail",
    description: "Guardrails da Cato Networks para detecção e mitigação abrangente de ameaças de IA.",
    category: "partner",
    logo: `${ASSET_PREFIX}cato_networks.svg`,
    tags: ["Segurança", "Detecção de Ameaças"],
  },
  {
    id: "prompt_security",
    name: "Prompt Security",
    description: "Protege contra ataques de injeção de prompt, vazamento de dados e outras ameaças de segurança de LLM.",
    category: "partner",
    logo: `${ASSET_PREFIX}prompt_security.png`,
    tags: ["Injeção de Prompt", "Segurança"],
  },
  {
    id: "lasso",
    name: "Lasso Guardrail",
    description: "Guardrails de moderação de conteúdo e segurança para implantações responsáveis de IA.",
    category: "partner",
    logo: `${ASSET_PREFIX}lasso.png`,
    tags: ["Moderação de Conteúdo"],
  },
  {
    id: "pangea",
    name: "Pangea Guardrail",
    description: "Guardrails de IA da Pangea para aplicações de IA seguras, compatíveis e confiáveis.",
    category: "partner",
    logo: `${ASSET_PREFIX}pangea.png`,
    tags: ["Conformidade", "Segurança"],
  },
  {
    id: "enkryptai",
    name: "EnkryptAI",
    description: "Plataforma de segurança e governança de IA para segurança e conformidade empresarial de IA.",
    category: "partner",
    logo: `${ASSET_PREFIX}enkrypt_ai.avif`,
    tags: ["Empresarial", "Governança"],
  },
  {
    id: "javelin",
    name: "Javelin Guardrails",
    description: "Gateway de IA com guardrails integrados para operações de IA seguras e compliantes.",
    category: "partner",
    logo: `${ASSET_PREFIX}javelin.png`,
    tags: ["Gateway", "Segurança"],
  },
  {
    id: "pillar",
    name: "Pillar Guardrail",
    description: "Plataforma de segurança de IA para monitoramento, teste e proteção de sistemas de IA.",
    category: "partner",
    logo: `${ASSET_PREFIX}pillar.jpeg`,
    tags: ["Monitoramento", "Segurança"],
  },
  {
    id: "akto",
    name: "Akto Guardrail",
    description: "Plataforma de segurança de IA da Akto.io com monitoramento automático e guardrails para aplicações de IA/ML.",
    category: "partner",
    logo: `${ASSET_PREFIX}akto.svg`,
    tags: ["Segurança", "Segurança", "Monitoramento"],
  },
  {
    id: "promptguard",
    name: "PromptGuard",
    description:
      "Gateway de segurança de IA com detecção de injeção de prompt, redação de PII, filtragem de tópicos, listas de bloqueio de entidades e detecção de alucinações. Auto-hospedável com integração de proxy.",
    category: "partner",
    logo: `${ASSET_PREFIX}promptguard.svg`,
    tags: ["Segurança", "Injeção de Prompt", "PII"],
    providerKey: "Promptguard",
    eval: {
      f1: 94.9,
      precision: 100.0,
      recall: 90.4,
      testCases: 5384,
      latency: "~150ms",
    },
  },
  {
    id: "xecguard",
    name: "XecGuard",
    description:
      "Gateway de segurança de IA CyCraft XecGuard. Escaneamento multi-política (injeção de prompt, conteúdo prejudicial, PII, aplicação de prompt do sistema) mais fundamentação de contexto RAG.",
    category: "partner",
    logo: `${ASSET_PREFIX}xecguard.svg`,
    tags: ["Segurança", "Política", "Fundamentação", "RAG"],
    providerKey: "Xecguard",
  },
  {
    id: "deepkeep",
    name: "DeepKeep AI Firewall",
    description:
      "DeepKeep AI Firewall para segurança abrangente de LLM — detecção de injeção de prompt, proteção de PII, moderação de conteúdo e aplicação de políticas com pipelines de guardrail configuráveis.",
    category: "partner",
    logo: `${ASSET_PREFIX}deepkeep.svg`,
    tags: ["Segurança", "Injeção de Prompt", "PII", "Firewall"],
    providerKey: "Deepkeep",
  },
  {
    id: "repelloai",
    name: "RepelloAI Argus",
    description:
      "RepelloAI Argus analisa prompts e respostas contra políticas configuradas por ativo no painel Repello.",
    category: "partner",
    logo: `${ASSET_PREFIX}repelloai.png`,
    tags: ["Segurança", "Política", "Injeção de Prompt"],
    providerKey: "Repelloai",
  },
  {
    id: "straiker",
    name: "Straiker",
    description:
      "Defesa de Guardrails Agênticos de IA: Injeção de Prompt Indireta/Direta, Uso Incorreto de Ferramentas, MCP e Habilidades Maliciosos",
    category: "partner",
    logo: `${ASSET_PREFIX}straiker.svg`,
    tags: ["Agêntico", "Injeção de Prompt", "Uso Incorreto de Ferramentas", "MCP", "Habilidades"],
    providerKey: "Straiker",
  },
];

export const ALL_CARDS = [...LITELLM_CONTENT_FILTER_CARDS, ...PARTNER_GUARDRAIL_CARDS];
